apiVersion: v1
kind: Service
metadata:
  name: firmstep-dotnet
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "common.labels" $ }}
spec:
  ports:
    - name: http
      port: {{.Values.fsdotnet.ports.httpPort.servicePort}}
      targetPort: {{.Values.fsdotnet.ports.httpPort.targetPort}}
  selector:
    {{ include "common.labels" $ }}
  type: LoadBalancer
